alias cat="bat"
alias cd="z"
alias cdi="zi"
alias lg="lazygit"
alias ls="eza --sort extension"
alias ls1="eza --tree --sort extension --level=1"
alias ls2="eza --tree --sort extension --level=2"
alias ls3="eza --tree --sort extension --level=3"
alias ls4="eza --tree --sort extension --level=4"
alias ls5="eza --tree --sort extension --level=5"
alias ls6="eza --tree --sort extension --level=6"
alias ls7="eza --tree --sort extension --level=7"
alias ls8="eza --tree --sort extension --level=8"
alias ls9="eza --tree --sort extension --level=9"
alias pip="pip3"
alias py="python3"
alias python="python3"
alias tcb="pbcopy"
alias vi="hx ."
alias vim="hx"

function loop() {
  cmd="$1"
  shift
  ls "$@" | entr -r sh -c "$cmd"
}

eval "$(starship init zsh)"
eval "$(thefuck --alias tf)"
eval "$(zoxide init zsh)"
