alias cat="bat"
alias cd="z"
alias cdi="zi"
alias lg="lazygit"
alias loop="entr"
alias ls="eza"
alias ls1="eza --tree --level=1"
alias ls2="eza --tree --level=2"
alias ls3="eza --tree --level=3"
alias ls4="eza --tree --level=4"
alias ls5="eza --tree --level=5"
alias ls6="eza --tree --level=6"
alias ls7="eza --tree --level=7"
alias ls8="eza --tree --level=8"
alias ls9="eza --tree --level=9"
alias pip="pip3"
alias py="python3"
alias python="python3"
alias tcb="pbcopy"
alias vi="hx ."
alias vim="hx"

eval "$(starship init zsh)"
eval "$(thefuck --alias tf)"
eval "$(zoxide init zsh)"
